-- 코드를 입력하세요

SELECT p.PRODUCT_ID, PRODUCT_NAME, PRICE*SUM(AMOUNT) AS 'TOTAL_SALES'
FROM FOOD_PRODUCT p join FOOD_ORDER o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY p.PRODUCT_ID
ORDER BY TOTAL_SALES desc, PRODUCT_ID asc;

# SELECT * FROM FOOD_PRODUCT;
