-- 코드를 입력하세요
SELECT DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON c.CAR_ID = h.CAR_ID
WHERE c.CAR_TYPE = '세단' and '2022-10-01'<=h.START_DATE AND h.START_DATE <='2022-10-31'
ORDER BY c.CAR_ID DESC;

# SELECT * FROM CAR_RENTAL_COMPANY_CAR;
