-- 코드를 입력하세요
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (SELECT CATEGORY, MAX(PRICE)
                         FROM FOOD_PRODUCT
                        WHERE CATEGORY = '과자' or CATEGORY='국' or CATEGORY='김치' or CATEGORY='식용유'
                         GROUP BY CATEGORY)
# GROUP BY CATEGORY
ORDER BY PRICE DESC;

# SELECT * FROM FOOD_PRODUCT;
