-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, SUM(PRICE) AS TOTAL_SALES 
FROM USED_GOODS_BOARD b join USED_GOODS_USER u 
on b.WRITER_ID=u.USER_ID
where b.STATUS='DONE'
group by u.USER_ID
having TOTAL_SALES>=700000
ORDER BY TOTAL_SALES;
