-- 코드를 입력하세요
# SELECT * FROM REST_INFO;

## FAVORITES만 MAX인 걸로 나오고 나머지는 SELECT의 첫번째 컬럼만 나온다
## => FOOD_TYPE과 FAVORITES을 연결시켜야 함
# SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES
# FROM REST_INFO
# GROUP BY FOOD_TYPE
# ORDER BY FOOD_TYPE DESC;

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES)
                                FROM REST_INFO
                                GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC;
