-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P, 
(SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT, PRODUCE_DATE FROM FOOD_ORDER  WHERE DATE(PRODUCE_DATE) BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID) O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;
